### ISSUE TITLE
Allow defining workspace name via cli flag

### ISSUE THREAD

**Issue by razaj92** [mvisonneau/tfcw#14]
It would be quite cool if we can set the workspace.name via a CLI flag or environment variable. 

This would help make the config more dynamic to apply across multiple workspaces.

Ideally we could allow variable interpolation with in the field itself

eg:
 ```
workspace {
    name = "my_app-${var.env}"
}
```

**Comment by mvisonneau** [comment]
I referenced the variable interpolation capability idea in #15.

I have been working on this one yesterday otherwise, I just need to polish a few things up :)

**Comment by mvisonneau** [comment]
pretty big commit but this should now be handled in https://github.com/mvisonneau/tfcw/commit/7c1621656e5e7dca33871b73716ebef4053df599

I also added some logic to be able to get the values from the Terraform remote backend directly. This aims to be able to completely omit the `tfc` block in the `tfcw.hcl` if necessary 👌

**Comment by razaj92** [comment]
Thanks @mvisonneau ! Nice one!
