### ISSUE TITLE
tfcw render does not find workspace

### ISSUE THREAD

**Issue by derekschauland** [mvisonneau/tfcw#61]
When using environment vars to build a new workspace in terraform cloud, I run tfcw render and the following output is displayed when --log-level debug is used:

bash-3.2$ tfcw --log-level debug render
DEBU[2020-10-27T14:30:12-05:00] Using config file at ./tfcw.hcl
DEBU[2020-10-27T14:30:12-05:00] Using TFC address 'https://app.terraform.io' from CLI flag (or env variable)
DEBU[2020-10-27T14:30:12-05:00] Using TFC token '***' from CLI flag (or env variable)
DEBU[2020-10-27T14:30:12-05:00] Using TFC organization 'my-org' from CLI flag (or env variable)
DEBU[2020-10-27T14:30:12-05:00] Using TFC workspace 'tf_infra_workspace' from CLI flag (or env variable)
DEBU[2020-10-27T14:30:13-05:00] Fetching workspace
INFO[2020-10-27T14:30:13-05:00] workspace 'tf_infra_workspace' does not exist on organization 'my-org', creating it..
DEBU[2020-10-27T14:30:13-05:00] Creating workspace
ERRO[2020-10-27T14:30:13-05:00] error fetching TFC workspace: resource not found
DEBU[2020-10-27T14:30:13-05:00] exited..                                      execution-time=779.160355ms

the workspace should have been created, and if it is then created and shows up in browser - still listed as not found.  Not sure what to try next
thanks

**Comment by mvisonneau** [comment]
👋 hey @derekschauland, indeed I found the issue, the error was actually misleading. It should be `error creating TFC workspace` I fixed it as part of a refactoring change : https://github.com/mvisonneau/tfcw/commit/c86e5701191d078939ac4d16ff1a7c8feb602302#diff-e50315482483bf3cd619740d3f05e38efd59c9813801382d7847562e38cc10d7R34

I am assuming the `resource not found` error returned by their API is related to your organization perhaps 🤔

**Comment by derekschauland** [comment]
does the new message provide any insight about what might be causing the issue?  When I was trying to get this working, I also tried including the backend "remote" config in terraform.tf - with the org and workspace in there, a terraform init built the workspace in our organization.  even when the workspace exists the message of not found was displayed.

I am not sure what might be missing from my config or HCL that would cause this to be the case...

**Comment by derekschauland** [comment]
I wonder if it has anything to do with using ENV vars for the details... 

I have exported values for the org and workspace to TFCW_ORGANIZATION and TFCW_WORKSPACE and when I double quote them in the HCL it seems to not complain - but the resources do not get updated

**Comment by mvisonneau** [comment]
interesting, would you mind sharing a sanitized version of your terraform.tf / tfcw.hcl and possible .env values? 🤔

**Comment by derekschauland** [comment]
A zip is attached with sensitive values removed - generally Azure ARM Env vars are needed and a token for TF Cloud

[Archive.zip](https://github.com/mvisonneau/tfcw/files/5465660/Archive.zip)

**Comment by mvisonneau** [comment]
Ok thanks! I believe you need something more like this to get it to work:

```hcl
# terraform.tf
terraform {
    backend "remote" {
        organization = "coterie-insurance"

        workspaces {
            name = "my-workspace"
        }
    }
}

provider "azurerm" {
    version = "2.33.0"
    features {}
}

# tfcw.hcl
envvar "ARM_TENANT_ID" {
  env {
     variable = "TFCW_VAR_ARM_TENANT_ID" 
  }
}

envvar "ARM_CLIENT_ID" {
  env {
      variable = "TFCW_VAR_ARM_CLIENT_ID"
  }
}

envvar "ARM_CLIENT_SECRET" {
  env {
      variable = "TFCW_VAR_ARM_CLIENT_SECRET"
  }
}

envvar "ARM_SUBSCRIPTION_ID" {
  env {
      variable = "TFCW_VAR_ARM_SUBSCRIPTION_ID"
  }
}
```

with the following environment variables set:

```bash
# .env
export TFCW_TOKEN="zVo2BHqG**************************************************************************************HevbHa4rYFFE"
export TFCW_VAR_ARM_CLIENT_ID="************************************"
export TFCW_VAR_ARM_CLIENT_SECRET="********************************"
export TFCW_VAR_ARM_TENANT_ID="42610b******************************"
export TFCW_VAR_ARM_SUBSCRIPTION_ID="e011**************************" 
```

**Comment by derekschauland** [comment]
I updated these files as shown above and added a tcf {} block for the address and token in tfcw.hcl and sourced .env then ran tfcw render and it ran with no issues... 

Not sure what I missed unless tfcw is expecting TFCW_ for env vars being exported rather than the usual TF_VAR (used by terraform) - can you make this clearer in the docs? 

thank you much for your assistance in getting this working and for creating this project.

**Comment by mvisonneau** [comment]
Absolutely I will attempt to make the configuration clearer. Basically all you need is `TFCW_TOKEN` being set if not defined within the `tfcw.hcl` file, which is recommended!

Then it is up to you to define the `organization` and the `workspace` settings within **terraform.tf** using:

```hcl
terraform {
    backend "remote" {
        organization = "my-organization"
        workspaces {
            name = "my-workspace"
        }
    }
}
```

or within **tfcw.hcl** using:

```hcl
tfc {
  organization = "my-organization"
  workspace {
    name = "my-workspace"
}
```

note that if both are defined, the values set in **tfcw.hcl** takes precedence over **terraform.tf**

**Comment by mvisonneau** [comment]
as for `TFCW_VAR_` this was purely arbitrary, as you can see in the [doc here](https://github.com/mvisonneau/tfcw/blob/main/docs/examples/provider_env.md), you can use whatever variable name you want. I would not recommend to use `TF_VAR_` prefixed ones in this context as this could cause confusion IMHO.

**Comment by derekschauland** [comment]
I think the TF_VAR stuff confused me and got things all caught up.  Since the .hcl takes priority, I think I will use it to configure the cloud workspace - this way it is separate from the terraform since I need to cloud workspace to do any work inside of terraform.

Then, the terraform.tf file just needs to point toward the cloud environment
